config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts, only: [:show, :index]
  namespace :admin do
    resources :posts, except: [:show, :index]

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :title, :summary, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"

  protected

  def check_admin
    redirect_to root_path, alert: "У Вас нет прав доступа к данной странице" unless current_user.admin?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_post, only: [ :edit, :update, :destroy ]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to  @post, success: 'Статья успешно создана'
    else
      flash.now[:error] = 'Статья не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to  @post, success: 'Статья успешно обновлена'
    else
      flash[:danger] = 'Статья не обновлена'
      render :edit
    end
  end


  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья успешно удалена'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :avatar)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    { success: "alert-success",
      error: "alert-danger",
      danger: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info",
    }[name.to_sym] || name
  end
end

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @post], html: {multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Редактирование статьи</h1>

<%= render 'form', post: @post %>

app/views/admin/posts/new.html.erb
<h1>Новая статья</h1>
<%= render 'form', post: @post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    </style>
  </head>

  <body class="bbg" >
    <div class="container">
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <ul class="nav navbar-nav, list-inline">
          <li class="nav-item active">
            <a class="nav-link" href="<%= posts_path %>">Статьи <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://vk.com/darkgolly">ВКонтакте</a>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
            <%= link_to 'Новая статья', new_admin_post_path, class: 'btn btn-outline-primary btn-sm' %>
            <% cache 'world-of-the-hour', expires_in: 2.second, class: "nav-link"  do %>
              <%= %w(dev mea hell door fuf uwu).sample %>
            <% end %>
          </li>
        </ul>





        <ul class="nav navbar-nav, list-inline">

            <li class="nav-item">
              <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %>">
            <button class="close" data-dismiss="alert">&times;</button>
            <% message %>
          </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
  <script>

    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
      var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    var disqus_config = function () {
      this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://newsblog-1.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><% t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: {multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2> <%= link_to post.title, post_path(post) %> </h2>
    <small>
      <time> <%= post.created_at.to_date.strftime("%d %B, %Y") %> </time>
      <% if user_signed_in? && current_user.admin? %>
        |
        <%= link_to 'Изменить', edit_admin_post_path(post) %>
        |
        <%= link_to 'Удалить', admin_post_path(post), method: :delete, data: {confirm: 'Вы уверенны?'} %>
      <% end %>
    </small>
  </section>
  <section class="post-summary clearfix">
    <%= image_tag post.avatar.url(:thumb), class: 'avt-thumbnail thumb' if post.avatar? %>
    <%= post.summary %>
  </section>
</article>

app/views/posts/index.html.erb
  <h1>Статьи</h1>

<section id='posts'>
  <% cache @posts do %>
    <%= render @posts %>
  <% end %>
</section>


<%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1> <%= @post.title %> </h1>
    <small>
      <time> <%= @post.created_at.to_date.strftime("%d %B, %Y") %> </time>
      <% if user_signed_in? && current_user.admin? %>
        |
        <%= link_to 'Изменить', edit_admin_post_path(@post) %>
        |
        <%= link_to 'Удалить', admin_post_path(@post), method: :delete, data: {confirm: 'Вы уверенны?'} %>
      <% end %>
    </small>
  </section>
  <section class="post-body">
    <%= image_tag @post.avatar.url(:large), class: 'avt-show' if @post.avatar? %>
    <%= @post.summary %>
    <p><%= @post.body %></p>
  </section>
</article>

<%= render 'disqus' %>